server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/khc41/spring-cloud-config
          #        native:
          #          search-locations: file://C:\Users\heechul\Desktop\work\native-file-repo
#          uri: file://C:\Users\heechul\Desktop\work\git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
